### ISSUE TITLE
Bounding box does not work

### ISSUE THREAD

**Issue by snthibaud** [sygic-travel/android-sdk#121]
I tried using the API to select places using a bounding box around Tokyo, but I get places from Italy back.
Specifically, I specified the bounds: 
`Bounds(north=36.19187, east=140.40828, south=35.29657, west=139.30148)`

**Comment by hrach** [comment]
Hi, thank your for reporting this! I discovered your reported bug in our v2 branch, so probably you are using this beta version. It's ok to use it, but be aware this is still beta though we are getting to stable release quite soon.

I'm pushing a fix and tagging a beta3. Thanks!

**Comment by hrach** [comment]
Beta-3 is already published: https://bintray.com/sygic-travel/maven/sdk/2.0.0-beta-3

**Comment by snthibaud** [comment]
Thank you!
